version: '2.1'

services:
  setup:
    image: samlysaml
    volumes:
      - ./setup:/setup
      - ./idps/${IDP_ID}:/sspdv
    command: /setup/init.sh
    environment:
      - IDP_ID
      - IDP_HOST
      - IDP_PORT
      - SECRET_SALT
      - PSWD
      - SP_BASEURL
      - SP_ACS_URI
      - SP_SLO_URI
      - SP_ENTITY_ID
      - SP_CERT_FILE
      - TIMEZONE

  idp:
    image: php:7.1-fpm-alpine3.8
    depends_on:
      - setup
    volumes_from:
      - setup
    expose:
      - 9000

  web:
    image: nginx:alpine
    depends_on:
      - idp
    ports:
      - ${IDP_PORT}:${IDP_PORT}
    volumes_from:
      - setup
    volumes:
      - ./idps/${IDP_ID}/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
      - ./idps/${IDP_ID}/cert:/etc/nginx/cert
    links:
      - idp
